### ISSUE TITLE
footer menü tasarımı

### ISSUE THREAD

**Issue by GoktugOzturk** [GoktugOzturk/tet-uzmanlar#2]
Footer menülerini koyunca patlak durdu.

**Comment by eraysays** [comment]
UL etiketini ve başlığını kapsayan bir div oluşturup "footer-list" class'ı eklemek gerekiyor. Tema dosyasında editleyebileceğim yeri bulamadım.

**Comment by GoktugOzturk** [comment]
footer-list classlarını ekleyince tasarım düzeldi. 

Sadece linklerin hover rengini düzenlemek lazım.

**Comment by eraysays** [comment]
footer linklerini kapsayan divi 'col-md-3' > 'col-md-3 col-sm-3 col-xs-6' classlarıyla değiştirmek gerekiyor.

**Comment by GoktugOzturk** [comment]
güncelledim.
